### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Korace0v0** [qsun1/Waymo-to-SDFStutio#1]
Hi, thanks for your kind work. This really helps me a lot. 

I am not really familiar with these two conventions. Can you tell me what's the difference between `process_waymo_to_sdf.py` and `process_waymo_to_sdfstudio.py` ? If I want to use waymo in sdfstudio, which file should I use?

I find that in `process_waymo_to_sdfstudio.py`, `camtoworld` is simply set as inverse `extrinsic`, which is `cam_to_ego` transform. Does this one exactly what sdfstudio need as camtoworld matrix?

**Comment by Korace0v0** [comment]
I understant it. Thanks for your work again.

**Comment by qiisun** [comment]
Hi, Sorry for my late reply. 

This project is *not* finished yet, looked like a little bit messy. As the sdfstudio does not provide off-the-shelf data converter for waymo-perception dataset., the main code is just a helper for converting the confusing waymo-perception .tfrecord file to understandable data format. Here is the specific [data format](https://github.com/autonomousvision/sdfstudio/blob/master/docs/sdfstudio-data.md#Dataset-format).

Thanks for your suggestions and I will PR to the base sdfstudio code as soon.

Cheers,
Qi

**Comment by Korace0v0** [comment]
Not a problem. This project indeed helps me a lot. Thanks for your kindness again.

Cheers,
Zhang
